# MSSQL Deployment Module
# Handles SQL Server installation with disk preparation

import uuid
import json
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException
import asyncpg

router = APIRouter(prefix="/api/v1/mssql", tags=["MSSQL"])

# Download URLs for Express/Developer editions
MSSQL_DOWNLOADS = {
    "2019": {
        "express": "https://go.microsoft.com/fwlink/?linkid=866658",
        "developer": "https://go.microsoft.com/fwlink/?linkid=866662"
    },
    "2022": {
        "express": "https://go.microsoft.com/fwlink/?linkid=2215158", 
        "developer": "https://go.microsoft.com/fwlink/?linkid=2215159"
    },
    "2025": {
        "express": "https://go.microsoft.com/fwlink/?linkid=2215158",  # Placeholder
        "developer": "https://go.microsoft.com/fwlink/?linkid=2215159"  # Placeholder
    }
}

# Edition info
EDITIONS = [
    {
        "id": "express",
        "name": "SQL Server Express",
        "free": True,
        "limits": "10GB DB, 1GB RAM, 4 cores",
        "versions": ["2019", "2022", "2025"],
        "downloadable": True,
        "requiresLicense": False
    },
    {
        "id": "developer",
        "name": "SQL Server Developer", 
        "free": True,
        "limits": "Dev/Test only, full features",
        "versions": ["2019", "2022", "2025"],
        "downloadable": True,
        "requiresLicense": False
    },
    {
        "id": "standard",
        "name": "SQL Server Standard",
        "free": False,
        "limits": "128GB RAM, 24 cores",
        "versions": ["2019", "2022", "2025"],
        "downloadable": False,
        "requiresLicense": True
    },
    {
        "id": "enterprise",
        "name": "SQL Server Enterprise",
        "free": False,
        "limits": "Unlimited",
        "versions": ["2019", "2022", "2025"],
        "downloadable": False,
        "requiresLicense": True
    }
]


# ============================================
# Pydantic Models
# ============================================

class DiskConfig(BaseModel):
    purpose: str = Field(..., description="data, log, tempdb, or backup")
    diskIdentifier: Dict[str, Any] = Field(..., description="How to identify the disk")
    driveLetter: str = Field(..., min_length=1, max_length=1)
    volumeLabel: str = Field(default="SQL_Volume")
    allocationUnitKb: int = Field(default=64)
    folder: str = Field(..., description="Folder name to create")


class DiskConfigSection(BaseModel):
    prepareDisks: bool = Field(default=True)
    disks: List[DiskConfig]


class SqlPaths(BaseModel):
    userDbDir: str = Field(default="D:\\Data")
    userDbLogDir: str = Field(default="E:\\Logs")
    tempDbDir: str = Field(default="F:\\TempDB")
    tempDbLogDir: str = Field(default="F:\\TempDB")
    backupDir: Optional[str] = Field(default=None)


class MssqlInstallRequest(BaseModel):
    targets: List[str] = Field(..., description="List of node IDs")
    edition: str = Field(..., description="express, developer, standard, enterprise")
    version: str = Field(..., description="2019, 2022, 2025")
    instanceName: str = Field(default="MSSQLSERVER")
    features: List[str] = Field(default=["SQLEngine"])
    saPassword: str = Field(..., min_length=8, description="SA password (not stored)")
    licenseKey: Optional[str] = Field(default=None, description="Required for Standard/Enterprise")
    collation: str = Field(default="Latin1_General_CI_AS")
    port: int = Field(default=1433)
    maxMemoryMb: Optional[int] = Field(default=None)
    tempDbFileCount: int = Field(default=4)
    tempDbFileSizeMb: int = Field(default=1024)
    includeSsms: bool = Field(default=True)
    diskConfig: Optional[DiskConfigSection] = Field(default=None)
    sqlPaths: Optional[SqlPaths] = Field(default=None)
    # For Standard/Enterprise - ISO path on network share
    isoPath: Optional[str] = Field(default=None, description="UNC path to SQL Server ISO")


class MssqlConfigCreate(BaseModel):
    name: str
    description: Optional[str] = None
    edition: str
    version: str
    instanceName: str = "MSSQLSERVER"
    features: List[str] = ["SQLEngine"]
    collation: str = "Latin1_General_CI_AS"
    port: int = 1433
    maxMemoryMb: Optional[int] = None
    tempDbFileCount: int = 4
    tempDbFileSizeMb: int = 1024
    includeSsms: bool = True
    diskConfigs: Optional[List[DiskConfig]] = None


# ============================================
# Script Generators
# ============================================

def generate_disk_prep_script(disk_config: DiskConfigSection) -> str:
    """Generate PowerShell script for disk preparation"""
    
    script_parts = [
        "# MSSQL Disk Preparation Script",
        "# Generated by Octofleet",
        "$ErrorActionPreference = 'Stop'",
        "",
        "function Prepare-SqlDisk {",
        "    param(",
        "        [int]$DiskNumber,",
        "        [string]$DriveLetter,",
        "        [string]$VolumeLabel,",
        "        [int]$AllocationUnitBytes,",
        "        [string]$FolderName",
        "    )",
        "",
        "    Write-Host \"Processing Disk $DiskNumber -> ${DriveLetter}:\"",
        "",
        "    $disk = Get-Disk -Number $DiskNumber -ErrorAction Stop",
        "",
        "    # Initialize if RAW",
        "    if ($disk.PartitionStyle -eq 'RAW') {",
        "        Write-Host \"  Initializing disk (GPT)...\"",
        "        Initialize-Disk -Number $DiskNumber -PartitionStyle GPT -Confirm:$false",
        "    }",
        "",
        "    # Check existing partitions",
        "    $existingPart = Get-Partition -DiskNumber $DiskNumber -ErrorAction SilentlyContinue |",
        "                    Where-Object { $_.DriveLetter -eq $DriveLetter }",
        "",
        "    if (-not $existingPart) {",
        "        Write-Host \"  Creating partition...\"",
        "        $part = New-Partition -DiskNumber $DiskNumber -UseMaximumSize -DriveLetter $DriveLetter",
        "",
        "        Write-Host \"  Formatting with ${AllocationUnitBytes}B allocation unit...\"",
        "        Format-Volume -DriveLetter $DriveLetter `",
        "                      -FileSystem NTFS `",
        "                      -AllocationUnitSize $AllocationUnitBytes `",
        "                      -NewFileSystemLabel $VolumeLabel `",
        "                      -Confirm:$false",
        "    } else {",
        "        Write-Host \"  Partition already exists\"",
        "    }",
        "",
        "    # Create folder",
        "    $folderPath = \"${DriveLetter}:\\${FolderName}\"",
        "    if (!(Test-Path $folderPath)) {",
        "        Write-Host \"  Creating folder $folderPath\"",
        "        New-Item -Path $folderPath -ItemType Directory -Force | Out-Null",
        "    }",
        "",
        "    Write-Host \"  ✓ Complete\"",
        "}",
        "",
    ]
    
    # Add calls for each disk
    for disk in disk_config.disks:
        disk_id = disk.diskIdentifier
        
        if "number" in disk_id:
            disk_num = disk_id["number"]
        elif "auto" in disk_id:
            # Auto-assign: find RAW disks
            idx = disk_id.get("index", 0)
            script_parts.append(f"# Auto-detect disk for {disk.purpose}")
            script_parts.append(f"$rawDisks = Get-Disk | Where-Object {{ $_.PartitionStyle -eq 'RAW' }} | Sort-Object Number")
            script_parts.append(f"$targetDisk = $rawDisks[{idx}]")
            script_parts.append(f"if (-not $targetDisk) {{ throw 'No RAW disk found for {disk.purpose}' }}")
            disk_num = "$targetDisk.Number"
        else:
            disk_num = disk_id.get("number", 1)
        
        alloc_bytes = disk.allocationUnitKb * 1024
        
        script_parts.append(f"Prepare-SqlDisk -DiskNumber {disk_num} `")
        script_parts.append(f"               -DriveLetter '{disk.driveLetter}' `")
        script_parts.append(f"               -VolumeLabel '{disk.volumeLabel}' `")
        script_parts.append(f"               -AllocationUnitBytes {alloc_bytes} `")
        script_parts.append(f"               -FolderName '{disk.folder}'")
        script_parts.append("")
    
    script_parts.append("Write-Host ''")
    script_parts.append("Write-Host '✅ Disk preparation complete'")
    
    return "\n".join(script_parts)


def generate_config_ini(request: MssqlInstallRequest, paths: SqlPaths) -> str:
    """Generate SQL Server ConfigurationFile.ini"""
    
    features = ",".join(request.features)
    
    ini_lines = [
        "[OPTIONS]",
        "ACTION=\"Install\"",
        f"FEATURES={features}",
        f"INSTANCENAME=\"{request.instanceName}\"",
        f"INSTANCEID=\"{request.instanceName}\"",
        "",
        "; Authentication",
        "SECURITYMODE=\"SQL\"",
        f"SAPWD=\"{request.saPassword}\"",
        "SQLSYSADMINACCOUNTS=\"BUILTIN\\Administrators\"",
        "",
        "; Collation",
        f"SQLCOLLATION=\"{request.collation}\"",
        "",
        "; Data Paths",
        f"INSTALLSQLDATADIR=\"{paths.userDbDir}\"",
        f"SQLUSERDBDIR=\"{paths.userDbDir}\"",
        f"SQLUSERDBLOGDIR=\"{paths.userDbLogDir}\"",
        f"SQLTEMPDBDIR=\"{paths.tempDbDir}\"",
        f"SQLTEMPDBLOGDIR=\"{paths.tempDbLogDir}\"",
    ]
    
    if paths.backupDir:
        ini_lines.append(f"SQLBACKUPDIR=\"{paths.backupDir}\"")
    
    ini_lines.extend([
        "",
        "; TempDB Configuration",
        f"SQLTEMPDBFILECOUNT={request.tempDbFileCount}",
        f"SQLTEMPDBFILESIZE={request.tempDbFileSizeMb}",
        "SQLTEMPDBFILEGROWTH=512",
        "SQLTEMPDBLOGFILESIZE=256",
        "SQLTEMPDBLOGFILEGROWTH=64",
        "",
        "; Network",
        "TCPENABLED=\"1\"",
        "NPENABLED=\"0\"",
        f"SQLSVCPORT={request.port}",
        "",
        "; Service Accounts",
        f"SQLSVCACCOUNT=\"NT Service\\MSSQL${request.instanceName}\"" if request.instanceName != "MSSQLSERVER" else "SQLSVCACCOUNT=\"NT Service\\MSSQLSERVER\"",
        "SQLSVCSTARTUPTYPE=\"Automatic\"",
        "BROWSERSVCSTARTUPTYPE=\"Automatic\"",
        "",
        "; License",
        "IACCEPTSQLSERVERLICENSETERMS=\"True\"",
    ])
    
    if request.licenseKey:
        ini_lines.append(f"PID=\"{request.licenseKey}\"")
    
    ini_lines.extend([
        "",
        "; Silent Install",
        "QUIET=\"True\"",
        "INDICATEPROGRESS=\"False\"",
        "UPDATEENABLED=\"False\"",
    ])
    
    return "\n".join(ini_lines)


def generate_install_script(request: MssqlInstallRequest, paths: SqlPaths) -> str:
    """Generate the main SQL Server installation script"""
    
    config_ini = generate_config_ini(request, paths)
    # Escape for PowerShell here-string
    config_ini_escaped = config_ini.replace("'", "''")
    
    download_url = MSSQL_DOWNLOADS.get(request.version, {}).get(request.edition, "")
    
    script = f'''# SQL Server {request.version} {request.edition.title()} Installation
# Generated by Octofleet
$ErrorActionPreference = 'Stop'

$setupDir = "$env:TEMP\\SQLSetup"
$configPath = "$setupDir\\ConfigurationFile.ini"

# Create setup directory
New-Item -Path $setupDir -ItemType Directory -Force | Out-Null

# Write configuration file
$configContent = @'
{config_ini_escaped}
'@
$configContent | Out-File -FilePath $configPath -Encoding ASCII

Write-Host "Configuration file written to $configPath"
'''

    if request.edition in ["express", "developer"]:
        # Download from Microsoft
        script += f'''
# Download SQL Server Setup
$downloadUrl = "{download_url}"
$setupExe = "$setupDir\\SQLEXPR_x64_ENU.exe"

Write-Host "Downloading SQL Server {request.version} {request.edition.title()}..."
Write-Host "URL: $downloadUrl"

$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest -Uri $downloadUrl -OutFile $setupExe -UseBasicParsing

Write-Host "Download complete. Extracting..."
Start-Process -FilePath $setupExe -ArgumentList "/QS /x:$setupDir\\extracted" -Wait -NoNewWindow

$actualSetup = Get-ChildItem -Path "$setupDir\\extracted" -Recurse -Filter "setup.exe" | Select-Object -First 1
if (-not $actualSetup) {{
    throw "setup.exe not found after extraction"
}}
$setupPath = $actualSetup.FullName
'''
    else:
        # Standard/Enterprise - expect ISO path
        if request.isoPath:
            script += f'''
# Mount ISO from network share
$isoPath = "{request.isoPath}"
Write-Host "Mounting ISO from $isoPath..."

$mountResult = Mount-DiskImage -ImagePath $isoPath -PassThru
$driveLetter = ($mountResult | Get-Volume).DriveLetter
$setupPath = "${{driveLetter}}:\\setup.exe"

if (!(Test-Path $setupPath)) {{
    throw "setup.exe not found on mounted ISO"
}}
'''
        else:
            script += '''
# Standard/Enterprise requires ISO path
throw "ISO path required for Standard/Enterprise edition. Set isoPath in request."
'''

    script += f'''
# Run SQL Server Setup
Write-Host "Starting SQL Server installation..."
Write-Host "This may take 20-45 minutes..."

$process = Start-Process -FilePath $setupPath `
    -ArgumentList "/ConfigurationFile=`"$configPath`" /IACCEPTSQLSERVERLICENSETERMS" `
    -Wait -PassThru -NoNewWindow

if ($process.ExitCode -ne 0) {{
    # Check summary log for details
    $logPath = "$env:ProgramFiles\\Microsoft SQL Server\\*\\Setup Bootstrap\\Log\\Summary.txt"
    $summaryLog = Get-ChildItem -Path $logPath -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($summaryLog) {{
        Write-Host "=== Installation Log ==="
        Get-Content $summaryLog.FullName | Select-Object -Last 50
    }}
    throw "SQL Server installation failed with exit code $($process.ExitCode)"
}}

Write-Host "✅ SQL Server installation complete"
'''

    # Memory configuration
    if request.maxMemoryMb:
        script += f'''
# Configure max server memory
Write-Host "Configuring max server memory to {request.maxMemoryMb} MB..."
$sqlCmd = @"
EXEC sp_configure 'show advanced options', 1;
RECONFIGURE;
EXEC sp_configure 'max server memory', {request.maxMemoryMb};
RECONFIGURE;
"@
Invoke-Sqlcmd -Query $sqlCmd -ServerInstance "localhost\\{request.instanceName}" -TrustServerCertificate
'''

    # Firewall
    script += f'''
# Configure Windows Firewall
Write-Host "Configuring firewall..."
New-NetFirewallRule -DisplayName "SQL Server ({request.instanceName})" `
    -Direction Inbound -Protocol TCP -LocalPort {request.port} -Action Allow -ErrorAction SilentlyContinue

New-NetFirewallRule -DisplayName "SQL Server Browser" `
    -Direction Inbound -Protocol UDP -LocalPort 1434 -Action Allow -ErrorAction SilentlyContinue
'''

    # SSMS
    if request.includeSsms:
        script += '''
# Install SQL Server Management Studio
Write-Host "Installing SSMS..."
$chocoPath = "C:\\ProgramData\\chocolatey\\bin\\choco.exe"
if (!(Test-Path $chocoPath)) {
    Write-Host "Installing Chocolatey first..."
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
}
& $chocoPath install sql-server-management-studio -y --no-progress
'''

    script += '''
# Cleanup
Write-Host "Cleaning up temporary files..."
Remove-Item -Path $setupDir -Recurse -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=========================================="
Write-Host "✅ SQL Server Installation Complete!"
Write-Host "=========================================="
'''

    return script


# ============================================
# API Endpoints
# ============================================

@router.get("/editions")
async def list_editions():
    """List available SQL Server editions"""
    return {"editions": EDITIONS}


@router.get("/downloads")
async def get_download_urls():
    """Get download URLs for Express/Developer editions"""
    return {"downloads": MSSQL_DOWNLOADS}


@router.post("/configs")
async def create_config(config: MssqlConfigCreate, db: asyncpg.Pool = Depends(lambda: None)):
    """Create a reusable MSSQL configuration profile"""
    # This will be injected properly when registered with the app
    pass  # Implemented in main.py


@router.get("/configs")
async def list_configs(db: asyncpg.Pool = Depends(lambda: None)):
    """List all MSSQL configuration profiles"""
    pass


@router.get("/configs/{config_id}")
async def get_config(config_id: str, db: asyncpg.Pool = Depends(lambda: None)):
    """Get a specific MSSQL configuration profile"""
    pass


@router.delete("/configs/{config_id}")
async def delete_config(config_id: str, db: asyncpg.Pool = Depends(lambda: None)):
    """Delete a MSSQL configuration profile"""
    pass


@router.post("/install")
async def install_mssql(request: MssqlInstallRequest, db: asyncpg.Pool = Depends(lambda: None)):
    """
    Install SQL Server on target nodes.
    
    This creates jobs for:
    1. Disk preparation (if diskConfig provided)
    2. SQL Server installation
    3. Post-installation configuration
    """
    pass


@router.get("/instances")
async def list_instances(node_id: Optional[str] = None, db: asyncpg.Pool = Depends(lambda: None)):
    """List all MSSQL instances across nodes"""
    pass


@router.get("/instances/{instance_id}")
async def get_instance(instance_id: str, db: asyncpg.Pool = Depends(lambda: None)):
    """Get details of a specific MSSQL instance"""
    pass


# Export for use in main.py
__all__ = [
    "router",
    "generate_disk_prep_script",
    "generate_install_script",
    "generate_config_ini",
    "MssqlInstallRequest",
    "DiskConfigSection",
    "SqlPaths",
    "MSSQL_DOWNLOADS",
    "EDITIONS"
]
