#!/usr/bin/env bash
#
# Octofleet PXE Zero-Touch Provisioning — Automated Setup
# Run as root on your provisioning server.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/BenediktSchackenberg/octofleet/main/provisioning/setup-pxe.sh | sudo bash
#   # or
#   sudo ./setup-pxe.sh
#
# Environment variables (optional — interactive prompts if not set):
#   OCTOFLEET_API_URL    Backend URL (e.g. http://192.168.0.49:8080)
#   OCTOFLEET_API_KEY    API key for backend auth
#   NFS_ISO_SOURCE       NAS/NFS path for ISOs (e.g. 192.168.0.24:/mnt/user/isos)
#   PXE_INTERFACE        Network interface for DHCP proxy (e.g. br0, eth0)
#   PXE_SERVER_IP        This server's IP (auto-detected if blank)
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }
ask()  { local var=$1 prompt=$2 default=$3; if [[ -z "${!var:-}" ]]; then read -rp "$(echo -e "${BLUE}[?]${NC} ${prompt} [${default}]: ")" val; eval "$var=\"${val:-$default}\""; fi; }

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  🐙 Octofleet PXE Provisioning — Auto Setup     ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── Check root ───────────────────────────────────────
[[ $EUID -eq 0 ]] || err "Please run as root (sudo)"

# ── Auto-detect server IP ────────────────────────────
AUTO_IP=$(hostname -I | awk '{print $1}')
ask PXE_SERVER_IP "PXE server IP" "$AUTO_IP"
ask OCTOFLEET_API_URL "Octofleet backend URL" "http://${PXE_SERVER_IP}:8080"
ask OCTOFLEET_API_KEY "Octofleet API key" ""
ask PXE_INTERFACE "Network interface for PXE" "$(ip route | grep default | awk '{print $5}' | head -1)"
ask NFS_ISO_SOURCE "NFS source for ISOs (empty = skip)" ""

# ── 1. Install dependencies ─────────────────────────
log "Installing dependencies..."
apt-get update -qq
apt-get install -y -qq nfs-kernel-server nfs-common docker.io docker-compose-v2 curl jq > /dev/null 2>&1
log "Dependencies installed"

# ── 2. Setup NFS for ISOs ───────────────────────────
mkdir -p /mnt/isos /mnt/pxe-images

if [[ -n "${NFS_ISO_SOURCE:-}" ]]; then
    if ! grep -q "$NFS_ISO_SOURCE" /etc/fstab 2>/dev/null; then
        echo "${NFS_ISO_SOURCE} /mnt/isos nfs defaults,_netdev 0 0" >> /etc/fstab
        log "Added NFS ISO mount to fstab"
    fi
    mount -a 2>/dev/null || warn "Could not mount NFS ISOs — check connectivity to ${NFS_ISO_SOURCE}"
fi

# ── 3. Auto-extract Ubuntu ISOs ─────────────────────
extract_iso() {
    local iso=$1 name=$2 mount_point="/mnt/pxe-images/${name}"
    
    if [[ -d "$mount_point/casper" ]]; then
        log "Already extracted: ${name}"
        return
    fi
    
    log "Extracting ${name} from ${iso}..."
    mkdir -p "$mount_point"
    mount -o loop,ro "$iso" /mnt/iso-tmp 2>/dev/null || { mkdir -p /mnt/iso-tmp; mount -o loop,ro "$iso" /mnt/iso-tmp; }
    cp -a /mnt/iso-tmp/* "$mount_point/" 2>/dev/null || true
    cp -a /mnt/iso-tmp/.disk "$mount_point/" 2>/dev/null || true
    umount /mnt/iso-tmp
    log "Extracted: ${name}"
}

mkdir -p /mnt/iso-tmp

# Auto-find Ubuntu ISOs
if [[ -d /mnt/isos ]]; then
    for iso in /mnt/isos/ubuntu-*-live-server-amd64.iso; do
        [[ -f "$iso" ]] || continue
        version=$(echo "$iso" | grep -oP 'ubuntu-\K[0-9]+\.[0-9]+')
        extract_iso "$iso" "ubuntu-${version}"
    done
fi

# ── 4. Configure NFS exports ────────────────────────
EXPORTS_CHANGED=false
for dir in /mnt/pxe-images/ubuntu-*/; do
    [[ -d "$dir" ]] || continue
    if ! grep -q "$dir" /etc/exports 2>/dev/null; then
        echo "${dir} *(ro,sync,no_subtree_check,insecure)" >> /etc/exports
        EXPORTS_CHANGED=true
    fi
done

if $EXPORTS_CHANGED; then
    exportfs -ra
    log "NFS exports updated"
else
    log "NFS exports already configured"
fi

systemctl enable --now nfs-kernel-server

# ── 5. Create docker-compose for PXE container ──────
PXE_DIR="/opt/octofleet-pxe"
mkdir -p "${PXE_DIR}"

cat > "${PXE_DIR}/docker-compose.yml" << YAML
services:
  octofleet-pxe:
    build: 
      context: ${PXE_DIR}/pxe-server
    ports:
      - "69:69/udp"
      - "4011:4011/udp"
      - "9080:80"
    volumes:
      - ${PXE_DIR}/config:/config
      - /mnt/isos:/isos:ro
      - /mnt/pxe-images:/pxe-images:ro
    environment:
      - OCTOFLEET_API=${OCTOFLEET_API_URL}
      - OCTOFLEET_API_KEY=${OCTOFLEET_API_KEY}
      - PXE_SERVER_IP=${PXE_SERVER_IP}
      - PXE_INTERFACE=${PXE_INTERFACE}
    network_mode: host
    restart: unless-stopped
YAML

# ── 6. Create iPXE boot script (auto-discovers images from API) ──
mkdir -p "${PXE_DIR}/config"

cat > "${PXE_DIR}/config/boot.ipxe" << 'IPXE'
#!ipxe

# Octofleet PXE Boot Menu
# Auto-generated by setup-pxe.sh

dhcp
set server-ip ${next-server}

:menu
menu Octofleet PXE Boot
item --gap -- ──── Provisioned Tasks ────
item provision    Boot assigned task (auto-detect by MAC)
item --gap -- ──── Manual Boot ────
item ubuntu2404  Ubuntu 24.04 LTS Server
item ubuntu2204  Ubuntu 22.04 LTS Server
item --gap -- ────────────────────
item shell       iPXE Shell
item exit        Exit to local boot
choose --timeout 10000 --default provision target && goto ${target}

:provision
# Query Octofleet API for MAC-based assignment
chain http://${server-ip}:9080/api/boot?mac=${mac:hexhyp} || goto menu

:ubuntu2404
kernel nfs://${server-ip}/mnt/pxe-images/ubuntu-24.04/casper/vmlinuz netboot=nfs nfsroot=${server-ip}:/mnt/pxe-images/ubuntu-24.04 ip=dhcp ---
initrd nfs://${server-ip}/mnt/pxe-images/ubuntu-24.04/casper/initrd
boot || goto menu

:ubuntu2204
kernel nfs://${server-ip}/mnt/pxe-images/ubuntu-22.04/casper/vmlinuz netboot=nfs nfsroot=${server-ip}:/mnt/pxe-images/ubuntu-22.04 ip=dhcp ---
initrd nfs://${server-ip}/mnt/pxe-images/ubuntu-22.04/casper/initrd
boot || goto menu

:shell
shell

:exit
exit
IPXE

# ── 7. Create systemd service ───────────────────────
cat > /etc/systemd/system/octofleet-pxe.service << EOF
[Unit]
Description=Octofleet PXE Provisioning Server
After=docker.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${PXE_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable octofleet-pxe.service
log "Systemd service created and enabled"

# ── 8. Register images in Octofleet API ─────────────
if [[ -n "${OCTOFLEET_API_KEY:-}" ]]; then
    for dir in /mnt/pxe-images/ubuntu-*/; do
        [[ -d "$dir" ]] || continue
        version=$(basename "$dir" | sed 's/ubuntu-//')
        
        log "Registering Ubuntu ${version} in Octofleet..."
        curl -sf -X POST "${OCTOFLEET_API_URL}/api/v1/provisioning/images" \
            -H "X-API-Key: ${OCTOFLEET_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{
                \"name\": \"ubuntu-${version}-server\",
                \"display_name\": \"Ubuntu ${version} LTS Server\",
                \"os_type\": \"linux\",
                \"os_version\": \"${version}\",
                \"architecture\": \"x64\",
                \"is_active\": true
            }" > /dev/null 2>&1 && log "  Registered Ubuntu ${version}" || warn "  Could not register Ubuntu ${version} (may already exist)"
        
        curl -sf -X POST "${OCTOFLEET_API_URL}/api/v1/provisioning/templates" \
            -H "X-API-Key: ${OCTOFLEET_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{
                \"platform\": \"linux\",
                \"display_name\": \"Ubuntu ${version} Auto-Install\",
                \"ipxe_template\": \"#!ipxe\nkernel nfs://${PXE_SERVER_IP}/mnt/pxe-images/ubuntu-${version}/casper/vmlinuz netboot=nfs nfsroot=${PXE_SERVER_IP}:/mnt/pxe-images/ubuntu-${version} ip=dhcp ---\ninitrd nfs://${PXE_SERVER_IP}/mnt/pxe-images/ubuntu-${version}/casper/initrd\nboot\",
                \"notes\": \"Auto-created by setup-pxe.sh\",
                \"is_active\": true
            }" > /dev/null 2>&1 && log "  Template created for Ubuntu ${version}" || warn "  Could not create template (may already exist)"
    done
fi

# ── 9. Summary ──────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  ✅ PXE Provisioning Setup Complete!             ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║                                                  ║"
echo "║  PXE Server IP:  ${PXE_SERVER_IP}$(printf '%*s' $((20 - ${#PXE_SERVER_IP})) '')║"
echo "║  TFTP:           port 69/udp                     ║"
echo "║  HTTP:           port 9080/tcp                   ║"
echo "║  NFS:            port 2049/tcp                   ║"
echo "║  Interface:      ${PXE_INTERFACE}$(printf '%*s' $((25 - ${#PXE_INTERFACE})) '')║"
echo "║                                                  ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  DHCP Config needed (on your router):            ║"
echo "║    next-server = ${PXE_SERVER_IP}$(printf '%*s' $((24 - ${#PXE_SERVER_IP})) '')║"
echo "║    BIOS file   = undionly.kpxe                   ║"
echo "║    UEFI file   = ipxe-x86_64.efi                ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  Manage templates: ${OCTOFLEET_API_URL}/provisioning"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "To start the PXE server now:"
echo "  cd ${PXE_DIR} && docker compose up -d --build"
echo ""
