#!/usr/bin/env bash
#
# OpenClaw Linux Agent Installer
# Downloads and installs the agent as a systemd service
#
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

INSTALL_DIR="/opt/openclaw-agent"
SERVICE_FILE="/etc/systemd/system/openclaw-agent.service"
GITHUB_RAW="https://raw.githubusercontent.com/BenediktSchackenberg/openclaw-windows-agent/main/linux-agent"

# Default values
API_URL=""
API_KEY=""
NODE_ID=""

usage() {
    cat << EOF
OpenClaw Linux Agent Installer

Usage: $0 [options]

Options:
    --api-url URL       API endpoint URL (required)
    --api-key KEY       API key for authentication (required)
    --node-id ID        Node identifier (default: hostname)
    --uninstall         Remove the agent
    -h, --help          Show this help

Example:
    $0 --api-url http://192.168.0.5:8080 --api-key my-secret-key

EOF
}

log() { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[-]${NC} $*" >&2; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root"
        exit 1
    fi
}

check_deps() {
    local missing=()
    for cmd in curl jq bc; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        warn "Missing dependencies: ${missing[*]}"
        
        if command -v apt-get &>/dev/null; then
            log "Installing dependencies with apt..."
            apt-get update -qq && apt-get install -y -qq "${missing[@]}"
        elif command -v dnf &>/dev/null; then
            log "Installing dependencies with dnf..."
            dnf install -y -q "${missing[@]}"
        elif command -v yum &>/dev/null; then
            log "Installing dependencies with yum..."
            yum install -y -q "${missing[@]}"
        elif command -v pacman &>/dev/null; then
            log "Installing dependencies with pacman..."
            pacman -Sy --noconfirm "${missing[@]}"
        else
            error "Cannot install dependencies automatically. Please install: ${missing[*]}"
            exit 1
        fi
    fi
}

install_agent() {
    log "Installing OpenClaw Linux Agent..."
    
    # Create directory
    mkdir -p "$INSTALL_DIR"
    
    # Download files
    log "Downloading agent files..."
    curl -fsSL "${GITHUB_RAW}/agent.sh" -o "${INSTALL_DIR}/agent.sh"
    curl -fsSL "${GITHUB_RAW}/openclaw-agent.service" -o "$SERVICE_FILE"
    
    # Make executable
    chmod +x "${INSTALL_DIR}/agent.sh"
    
    # Create config
    log "Creating configuration..."
    cat > "${INSTALL_DIR}/config.env" << EOF
# OpenClaw Linux Agent Configuration
# Generated by installer on $(date)

API_URL="${API_URL}"
API_KEY="${API_KEY}"
NODE_ID="${NODE_ID:-$(hostname)}"
PUSH_INTERVAL=1800
JOB_POLL_INTERVAL=60
LOG_FILE="/var/log/openclaw-agent.log"
EOF
    
    chmod 600 "${INSTALL_DIR}/config.env"
    
    # Create log file
    touch /var/log/openclaw-agent.log
    
    # Reload systemd
    log "Enabling systemd service..."
    systemctl daemon-reload
    systemctl enable openclaw-agent
    systemctl start openclaw-agent
    
    log "Installation complete!"
    echo ""
    echo -e "${BLUE}Agent Status:${NC}"
    systemctl status openclaw-agent --no-pager || true
    echo ""
    echo -e "${GREEN}OpenClaw Linux Agent installed successfully!${NC}"
    echo ""
    echo "Useful commands:"
    echo "  View logs:    journalctl -u openclaw-agent -f"
    echo "  Check status: systemctl status openclaw-agent"
    echo "  Restart:      systemctl restart openclaw-agent"
    echo "  Edit config:  nano ${INSTALL_DIR}/config.env"
}

uninstall_agent() {
    log "Uninstalling OpenClaw Linux Agent..."
    
    if systemctl is-active --quiet openclaw-agent 2>/dev/null; then
        systemctl stop openclaw-agent
    fi
    
    if systemctl is-enabled --quiet openclaw-agent 2>/dev/null; then
        systemctl disable openclaw-agent
    fi
    
    rm -f "$SERVICE_FILE"
    rm -rf "$INSTALL_DIR"
    rm -f /var/log/openclaw-agent.log
    
    systemctl daemon-reload
    
    log "Agent uninstalled successfully"
}

# Parse arguments
UNINSTALL=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --api-url)
            API_URL="$2"
            shift 2
            ;;
        --api-key)
            API_KEY="$2"
            shift 2
            ;;
        --node-id)
            NODE_ID="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Main
check_root

if [[ "$UNINSTALL" == "true" ]]; then
    uninstall_agent
    exit 0
fi

# Validate required params
if [[ -z "$API_URL" ]]; then
    error "Missing required option: --api-url"
    usage
    exit 1
fi

if [[ -z "$API_KEY" ]]; then
    error "Missing required option: --api-key"
    usage
    exit 1
fi

check_deps
install_agent
