CIS_TEMPLATES = {
    "cis-win-server-2022-l1": {
        "id": "cis-win-server-2022-l1",
        "name": "CIS Windows Server 2022/2025 L1",
        "description": "CIS Benchmark Level 1 for Windows Server 2022/2025 — essential security hardening",
        "baseline_type": "custom",
        "rules": [
            {"rule_name": "Windows Firewall Service Running", "rule_type": "service",
             "expected_value": {"service": "MpsSvc", "state": "running"},
             "severity": "critical", "remediation_action": {"type": "start_service", "service": "MpsSvc"}},
            {"rule_name": "Windows Update Service Enabled", "rule_type": "service",
             "expected_value": {"service": "wuauserv", "state": "running"},
             "severity": "high", "remediation_action": {"type": "start_service", "service": "wuauserv"}},
            {"rule_name": "Remote Registry Disabled", "rule_type": "service",
             "expected_value": {"service": "RemoteRegistry", "state": "stopped"},
             "severity": "high", "remediation_action": {"type": "run_command", "command": "Stop-Service RemoteRegistry; Set-Service RemoteRegistry -StartupType Disabled"}},
            {"rule_name": "WinRM Service Running", "rule_type": "service",
             "expected_value": {"service": "WinRM", "state": "running"},
             "severity": "medium", "remediation_action": {"type": "start_service", "service": "WinRM"}},
            {"rule_name": "Blank Password Use Limited", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa", "value_name": "LimitBlankPasswordUse", "expected": "1", "operator": "eq"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LimitBlankPasswordUse -Value 1"}},
            {"rule_name": "Security Event Log Min Size", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security", "value_name": "MaxSize", "expected": "20480", "operator": "gte"},
             "severity": "high", "remediation_action": {"type": "run_command", "command": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security' -Name MaxSize -Value 20971520"}},
            {"rule_name": "SMBv1 Disabled", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters", "value_name": "SMB1", "expected": "0", "operator": "eq"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanmanServer\\Parameters' -Name SMB1 -Value 0"}},
            {"rule_name": "NTLMv2 Required", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa", "value_name": "LmCompatibilityLevel", "expected": "3", "operator": "gte"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LmCompatibilityLevel -Value 5"}},
            {"rule_name": "Windows Defender / Antivirus Present", "rule_type": "software",
             "expected_value": {"package": "Windows Defender", "operator": "installed"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "try { Install-WindowsFeature -Name Windows-Defender -ErrorAction Stop } catch { Add-WindowsCapability -Online -Name 'Microsoft.Windows.Defender~~~~' -ErrorAction Stop }"}},
        ]
    },
    "cis-win11-enterprise-l1": {
        "id": "cis-win11-enterprise-l1",
        "name": "CIS Windows 11 Enterprise L1",
        "description": "CIS Benchmark Level 1 for Windows 11 Enterprise — workstation security hardening",
        "baseline_type": "custom",
        "rules": [
            {"rule_name": "Windows Defender Antivirus Running", "rule_type": "service",
             "expected_value": {"service": "WinDefend", "state": "running"},
             "severity": "critical", "remediation_action": {"type": "start_service", "service": "WinDefend"}},
            {"rule_name": "BitLocker Drive Encryption Running", "rule_type": "service",
             "expected_value": {"service": "BDESVC", "state": "running"},
             "severity": "high", "remediation_action": {"type": "start_service", "service": "BDESVC"}},
            {"rule_name": "UAC Enabled", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "value_name": "EnableLUA", "expected": "1", "operator": "eq"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableLUA -Value 1"}},
            {"rule_name": "Secure Boot Enabled", "rule_type": "registry",
             "expected_value": {"key_path": "SecureBoot", "value_name": "UEFISecureBootEnabled", "expected": "1", "operator": "eq"},
             "severity": "high", "remediation_action": {"type": "none"}},
            {"rule_name": "Windows Firewall Domain Profile ON", "rule_type": "registry",
             "expected_value": {"key_path": r"HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\DomainProfile", "value_name": "EnableFirewall", "expected": "1", "operator": "eq"},
             "severity": "critical", "remediation_action": {"type": "run_command", "command": "Set-NetFirewallProfile -Profile Domain -Enabled True"}},
            {"rule_name": "Microsoft Edge or Approved Browser Installed", "rule_type": "software",
             "expected_value": {"package": "Microsoft Edge", "operator": "installed"},
             "severity": "medium", "remediation_action": {"type": "install_package", "package": "microsoft-edge"}},
        ]
    }
}
CHOCO_PACKAGES = {
    "notepad++": "notepadplusplus",
    "notepadplusplus": "notepadplusplus",
    "7zip": "7zip",
    "7-zip": "7zip",
    "vlc": "vlc",
    "git": "git",
    "vscode": "vscode",
    "vs-code": "vscode",
    "python": "python",
    "nodejs": "nodejs-lts",
    "node": "nodejs-lts",
    "chrome": "googlechrome",
    "firefox": "firefox",
    "putty": "putty",
    "winscp": "winscp",
    "filezilla": "filezilla",
    "sysinternals": "sysinternals",
    "powershell": "powershell-core",
    "pwsh": "powershell-core",
}
