"""Report helper functions extracted from main.py"""
from typing import List
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import Table, TableStyle, Paragraph, Spacer
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import tempfile


def style_excel_header(ws, row=1):
    """Apply header styling to first row."""
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )
    for cell in ws[row]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')
        cell.border = thin_border


def auto_column_width(ws):
    """Auto-adjust column widths."""
    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = min(max_length + 2, 50)
        ws.column_dimensions[column].width = adjusted_width



def create_header_footer(canvas, doc, title: str):
    """Add header and footer to PDF pages"""
    canvas.saveState()
    
    # Header
    canvas.setFont('Helvetica-Bold', 10)
    canvas.setFillColor(colors.HexColor('#1a1a2e'))
    canvas.drawString(50, A4[1] - 30, f"Octofleet - {title}")
    canvas.drawRightString(A4[0] - 50, A4[1] - 30, datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'))
    
    # Footer
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(50, 30, "Generated by Octofleet Endpoint Management Platform")
    canvas.drawRightString(A4[0] - 50, 30, f"Page {doc.page}")
    
    canvas.restoreState()



def create_status_table(data: List[List], col_widths: List[float] = None) -> Table:
    """Create a styled table for reports"""
    table = Table(data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('TOPPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    return table



def create_pie_chart(data: dict, title: str, filename: str) -> str:
    """Create a pie chart and save to temp file."""
    fig, ax = plt.subplots(figsize=(4, 4))
    
    # Filter out zero values
    filtered = {k: v for k, v in data.items() if v > 0}
    if not filtered:
        filtered = {"No Data": 1}
    
    colors_map = {
        "online": "#22c55e",
        "away": "#f59e0b", 
        "offline": "#ef4444",
        "critical": "#dc2626",
        "high": "#f97316",
        "medium": "#eab308",
        "low": "#22c55e",
        "success": "#22c55e",
        "failed": "#ef4444",
        "running": "#3b82f6",
        "pending": "#6b7280"
    }
    
    chart_colors = [colors_map.get(k.lower(), "#6b7280") for k in filtered.keys()]
    
    wedges, texts, autotexts = ax.pie(
        filtered.values(), 
        labels=filtered.keys(),
        autopct='%1.1f%%',
        colors=chart_colors,
        startangle=90
    )
    ax.set_title(title, fontsize=12, fontweight='bold')
    
    plt.tight_layout()
    filepath = f"/tmp/{filename}"
    plt.savefig(filepath, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()
    return filepath


